### ISSUE TITLE
Only print methods that are too long

### ISSUE THREAD

**Issue by lenahartmann00** [lell170/searchLongMethodNamesInJavaFilesOfProjectDirectories#2]
When calling `longmethods` the user is interesting in displaying the methods that are too long (so that he can fix it). Seeing all the other methods makes the output very long and unreadable (the user has to scroll to the top in order to find the "bad" methods).
Because of this only the methods should be shown that are too long and not those who have an acceptable size.

**Comment by lell170** [comment]
fixed in #7
